## Configuration file for MineCombat

# Preparation time before starting game (seconds)
# default: 60 seconds (1 min.)
preparation-time: 60

# Time for doing game (seconds)
# default: 600 seconds (10 min.)
game-time: 600

# Minimum players to start game (players)
# default: 4 players (4 hum.)
min-players: 4

# Allow player to suicide
# default: false (cannot suicide)
allow-suicide: false
